---
framework: lanyon
onefile: False
mode: selfcontained
url: {lib: ../libraries}
---

## Research

.message My research focuses on two broad areas: retail operations and empirical methodologies in Operations Management

### Papers Published

1. __A Demand Estimation Procedure for Retail Assortment Optimization with Results from Implementations__ (forthcoming in _Management Science_): In this paper, we focus on the retailer’s problem of (a) forecasting demand for products in a category (including those that they have never carried before), (b) optimizing the selected assortment, and (c) customizing the assortment by store to maximize chain­wide revenues or profits. We develop algorithms for demand forecasting and assortment optimization, and demonstrate their use in planning the tire assortment of a major tire retailer (in the top 5) and the snack cake assortment of a regional convenience chain. This paper is forthcoming at Management Science.

2.  __Measuring Seat Value in Stadiums and Theaters__. In this paper, we address pricing and revenue management (RM) issues in ticket retailing for stadiums and theaters. We develop a yardstick to measure seat value derived by customers attending an event in a stadium/theater and study how it relates to the location of the seat relative to the field/stage. We apply our methodology to a baseball dataset and derive several interesting insights. This paper has been published in _Production and Operations Management_.

3. __Which Products Should You Stock?__ In this paper, we discuss a data­driven approach to assortment optimization that allows retailers to make better decisions on what products to stock. This was published in the _Harvard Business Review_ in Nov 2012.

### Papers In-Progress

I am working on 5 papers, which are in different stages of completion.

1. __Revenue Management of Experience Goods: Linking Seat Value and Willingness to Pay.__ In this paper, we consider the static pricing problem faced by a firm selling an assortment of experience goods to a deterministic population of consumers. A key input to solve for the optimal pricing scheme in such settings is the distribution of willingness­to­pay (WTP) across consumers. We provide a methodology to estimate the distribution of WTP across consumers using consumer surveys and apply it to real data from a sports franchise to estimate the distribution of WTP and solve for optimal ticket prices across seat locations. I am collaborating with Prof. Senthil Veeraraghavan at the Wharton School.

2. __Assortment Planning: A Sensitivity Analysis.__ In this paper, I investigate two important issues in assortment modeling: the impact of (1) ignoring stockout substitution and (2) using an incorrectly specified choice model, on the optimal assortment and profits. I quantify their effects in terms of the maximum percentage gap from the optimal solution and study its variation across a wide range of values for key parameters specifying the problem. My research reveals several interesting insights which have significant implications for retail assortment practice. This paper is under preparation for submission to Manufacturing & Service Operations Management.

3.  __Thriving in a Recession: The Role of Operations Based Strategies.__ In this paper, we empirically analyze the operations­based strategies pursued by firms during and around a recession with the objective of understanding what role (if any) such strategies play in successfully surviving a recession and thriving once the economy picks up. In particular, we explore the performance of inventory based strategies vs. non­inventory based strategies. We use data from financial databases COMPUSTAT, CRSP and the Monthly Retail Trade reports to track various operating metrics including GMROI, Inventory Turnover etc. at the firm level across years, and connect it with financial performance over the same period. I am collaborating with Prof. Saibal Ray and Prof. Mehmet Gumus on this paper.

4.  __Assortment Planning under Competition with a Dominant Retailer.__ In this paper, we investigate the assortment planning problem in the presence of a dominant retailer and competitive fringe. I am collaborating with my PhD student Hedayat Alibeiki and Prof. Shanling Li on this paper.

5. __Exploring the Equivalence of Mixture Models for Duration Data.__ In this paper, we explore the relationship between the Exponential Gamma and Beta Geometric distributions, commonly used to model duration data. We identify several equivalencies between the parameters of the two distributions. Our research has significant implications for modeling of duration data. I am collaborating with Prof. Peter Fader at the Wharton School and Prof. Bruce Hardie at the London Business School.


<style>
  li{text-align: justify;}
</style>

