---
framework: lanyon
onefile: False
mode: selfcontained
url: {lib: ../libraries}
---

## Publications

1. Fisher, M., Vaidyanathan, R., __[A Demand Estimation Procedure for Retail Assortment Optimization with Results from Implementations](https://opimweb.wharton.upenn.edu/files/?whdmsaction=public:main.file&fileID=7041)__, _Management Science_ (forthcoming)

2. Fisher, M., Vaidyanathan, R., __[Which Products Should You Stock?](http://hbr.org/2012/11/which-products-should-you-stock/ar/1)__, _Harvard Business Review_, November 2012

3. Veeraraghavan, S., Vaidyanathan, R., __[Measuring Seat Value in Stadiums and Theaters](http://onlinelibrary.wiley.com/doi/10.1111/j.1937-5956.2011.01249.x/abstract)__, _Production and Operations Management_, v. 21, no. 1, 2012, pp. 49-68

4. Kok, A. G., Fisher, M., and Vaidyanathan, R., __[Assortment Planning: Review of Literature and Industry Practice](http://qbox.wharton.upenn.edu/documents/opim/research/APchapter.pdf)__, in N. Agarwal and S.A. Smith (ed.) _[Retail Supply Chain Management: Quantitative Models and Empirical Studies](http://www.amazon.com/Retail-Supply-Chain-Management-International/dp/0387789022)_, Springer, 2009, 99pp

5. Vaidyanathan, R., Santhanam, S., and Ramamurti, R., __[Static and Dynamic Analysis of an Aerofoil Bladed Disc using the concept of Cyclic Symmetry](http://onlinelibrary.wiley.com/doi/10.1002/cnm.571/abstract)__, _Communications in Numerical Methods in Engineering_, v. 19, no. 12, 2003, pp. 22-50.

<style>
  li{
  	text-align: justify;
  }
</style>
